"""Missing-document follow-up micro-automation.

This is the "dashboard to action" proof for OpsPilot. It reads the raw OpsPilot
requests CSV (RAW fields only -- request_id, required_documents_missing, owner,
priority, submitted_date; it never touches the classification module), finds
requests that are missing required documents, and for each one:

  1. Writes a plain-text follow-up message into an outbox/ directory.
  2. Appends an action row to audit_log.csv.

Every action carries an idempotency key (request_id + rule name). Before acting
on a request, the script checks the existing audit log for that key, so a second
run creates zero new outbox files and zero new audit rows.

Usage:
    py automations/missing_document_followup.py
    py automations/missing_document_followup.py --data data/opspilot_requests.csv \
        --outbox outbox --audit-log audit_log.csv

Run with --help for all options.
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import re
from pathlib import Path


RULE_NAME = "missing_document_followup"
TRUE_VALUES = {"true", "1", "yes", "y", "t"}

AUDIT_HEADER = ["timestamp", "request_id", "rule", "idempotency_key", "action", "outbox_file"]


def _repo_root() -> Path:
    # automations/missing_document_followup.py -> repo root is one level up.
    return Path(__file__).resolve().parent.parent


def _is_true(value: str | None) -> bool:
    return (value or "").strip().lower() in TRUE_VALUES


def idempotency_key(request_id: str, rule_name: str) -> str:
    return f"{request_id}::{rule_name}"


def _safe_slug(value: str) -> str:
    """Reduce an untrusted field to a filename-safe slug.

    Prevents a crafted request_id (e.g. "../../x") from escaping the outbox
    directory when it is used to build an output filename. Harmless for the
    synthetic "REQ-#####" ids, but the automation is designed to point at real
    data next.
    """
    return re.sub(r"[^A-Za-z0-9._-]", "_", value)[:120] or "unknown"


def load_existing_keys(audit_log: Path) -> set[str]:
    """Return the set of idempotency keys already recorded in the audit log."""
    keys: set[str] = set()
    if not audit_log.exists():
        return keys
    with audit_log.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            key = (row.get("idempotency_key") or "").strip()
            if key:
                keys.add(key)
    return keys


def build_followup_message(row: dict, rule_name: str) -> str:
    request_id = row.get("request_id", "").strip()
    owner = row.get("owner", "").strip() or "Unassigned owner"
    priority = row.get("priority", "").strip() or "Unspecified"
    submitted = row.get("submitted_date", "").strip() or "unknown date"
    return (
        f"Follow-up: missing documents on request {request_id}\n"
        f"Rule: {rule_name}\n"
        f"Owner: {owner}\n"
        f"Priority: {priority}\n"
        f"Submitted: {submitted}\n"
        "\n"
        f"Hi {owner},\n"
        "\n"
        f"Request {request_id} is flagged as missing one or more required documents, "
        "which is holding up its progress. Please upload the outstanding documentation "
        "or reply with a status update so we can keep this moving.\n"
        "\n"
        f"This is an automated reminder generated by the OpsPilot {rule_name} rule.\n"
    )


def run(
    data_path: Path,
    outbox_dir: Path,
    audit_log: Path,
    rule_name: str = RULE_NAME,
) -> dict:
    if not data_path.exists():
        raise FileNotFoundError(f"Requests CSV not found: {data_path}")

    outbox_dir.mkdir(parents=True, exist_ok=True)

    existing_keys = load_existing_keys(audit_log)
    audit_exists = audit_log.exists()

    scanned = 0
    missing = 0
    written = 0
    skipped = 0

    new_audit_rows: list[list[str]] = []
    timestamp = _dt.datetime.now().isoformat(timespec="seconds")

    with data_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            scanned += 1
            if not _is_true(row.get("required_documents_missing")):
                continue
            missing += 1

            request_id = (row.get("request_id") or "").strip()
            if not request_id:
                continue

            key = idempotency_key(request_id, rule_name)
            if key in existing_keys:
                skipped += 1
                continue

            # Mark the key as handled immediately so duplicate request_ids in the
            # same file cannot double-write within a single run.
            existing_keys.add(key)

            outbox_file = outbox_dir / f"{_safe_slug(request_id)}_{_safe_slug(rule_name)}.txt"
            # Defense in depth: never write outside the outbox directory.
            if not outbox_file.resolve().is_relative_to(outbox_dir.resolve()):
                raise ValueError(f"Refusing to write outside outbox: {outbox_file}")
            outbox_file.write_text(build_followup_message(row, rule_name), encoding="utf-8")
            written += 1

            new_audit_rows.append(
                [
                    timestamp,
                    request_id,
                    rule_name,
                    key,
                    "followup_message_written",
                    str(outbox_file),
                ]
            )

    if new_audit_rows:
        write_header = not audit_exists
        with audit_log.open("a", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            if write_header:
                writer.writerow(AUDIT_HEADER)
            writer.writerows(new_audit_rows)

    return {
        "scanned": scanned,
        "missing": missing,
        "written": written,
        "skipped": skipped,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    root = _repo_root()
    parser = argparse.ArgumentParser(
        description=(
            "Detect OpsPilot requests missing required documents, write one "
            "follow-up message per request into an outbox, and audit-log each "
            "action with an idempotency key (safe to re-run)."
        )
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=root / "data" / "opspilot_requests.csv",
        help="Path to opspilot_requests.csv (default: data/opspilot_requests.csv).",
    )
    parser.add_argument(
        "--outbox",
        type=Path,
        default=root / "outbox",
        help="Directory to write follow-up messages into (default: outbox/).",
    )
    parser.add_argument(
        "--audit-log",
        type=Path,
        default=root / "audit_log.csv",
        help="Audit log CSV to append actions to (default: audit_log.csv).",
    )
    parser.add_argument(
        "--rule-name",
        default=RULE_NAME,
        help=f"Rule name used in the idempotency key (default: {RULE_NAME}).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    result = run(args.data, args.outbox, args.audit_log, args.rule_name)
    print("Missing-document follow-up automation complete.")
    print(f"  Requests scanned:        {result['scanned']}")
    print(f"  Missing-document flags:  {result['missing']}")
    print(f"  New follow-ups written:  {result['written']}")
    print(f"  Already handled (skipped): {result['skipped']}")
    print(f"  Outbox: {args.outbox}")
    print(f"  Audit log: {args.audit_log}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
