"""Missing-document follow-up micro-automation.

This is the "dashboard to action" proof for OpsPilot. It reads the raw OpsPilot
requests CSV (RAW fields only -- request_id, required_documents_missing, owner,
priority, submitted_date; it never touches the classification module), finds
requests that are missing required documents, and for each one:

  1. Writes a plain-text follow-up message into an outbox/ directory.
  2. Appends an action row to audit_log.csv.

Every action carries an idempotency key (request_id + rule name). Before acting
on a request, the script checks the existing audit log for that key, so a second
run creates zero new outbox files and zero new audit rows.

Usage:
    py automations/missing_document_followup.py
    py automations/missing_document_followup.py --data data/opspilot_requests.csv \
        --outbox outbox --audit-log audit_log.csv

Run with --help for all options.
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import re
from pathlib import Path


RULE_NAME = "missing_document_followup"
TRUE_VALUES = {"true", "1", "yes", "y", "t"}

AUDIT_HEADER = ["timestamp", "request_id", "rule", "idempotency_key", "action", "outbox_file"]


def _repo_root() -> Path:
    # automations/missing_document_followup.py -> repo root is one level up.
    return Path(__file__).resolve().parent.parent


def _is_true(value: str | None) -> bool:
    return (value or "").strip().lower() in TRUE_VALUES


def idempotency_key(request_id: str, rule_name: str) -> str:
    return f"{request_id}::{rule_name}"


def _safe_slug(value: str) -> str:
    """Reduce an untrusted field to a filename-safe slug.

    Prevents a crafted request_id (e.g. "../../x") from escaping the outbox
    directory when it is used to build an output filename. Harmless for the
    synthetic "REQ-#####" ids, but the automation is designed to point at real
    data next.
    """
    return re.sub(r"[^A-Za-z0-9._-]", "_", value)[:120] or "unknown"


def _parse_ts(value: str) -> _dt.datetime | None:
    try:
        return _dt.datetime.fromisoformat(value)
    except (ValueError, TypeError):
        return None


def load_key_last_seen(audit_log: Path) -> dict[str, _dt.datetime]:
    """Map each idempotency key to the most recent timestamp it was acted on.

    Used both for the plain "already handled" check and for the optional
    ``--window-days`` re-trigger logic.
    """
    last_seen: dict[str, _dt.datetime] = {}
    if not audit_log.exists():
        return last_seen
    with audit_log.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            key = (row.get("idempotency_key") or "").strip()
            if not key:
                continue
            ts = _parse_ts((row.get("timestamp") or "").strip())
            if ts is None:
                # Undated legacy row: treat as "seen forever" so we never re-send.
                last_seen[key] = _dt.datetime.max
            elif key not in last_seen or ts > last_seen[key]:
                last_seen[key] = ts
    return last_seen


def handled_keys(
    last_seen: dict[str, _dt.datetime], now: _dt.datetime, window_days: int | None
) -> set[str]:
    """Keys that should be treated as already-handled for this run.

    Default (``window_days is None``): any key ever recorded is handled -- the
    "safe to re-run, zero duplicates" guarantee the README advertises. With a
    window, a key becomes eligible again once its last action is older than the
    window, which supports a reminder/escalation ladder without ever double-sending
    inside the window.
    """
    if window_days is None:
        return set(last_seen)
    cutoff = now - _dt.timedelta(days=window_days)
    return {key for key, ts in last_seen.items() if ts >= cutoff}


def build_followup_message(row: dict, rule_name: str) -> str:
    request_id = row.get("request_id", "").strip()
    owner = row.get("owner", "").strip() or "Unassigned owner"
    priority = row.get("priority", "").strip() or "Unspecified"
    submitted = row.get("submitted_date", "").strip() or "unknown date"
    return (
        f"Follow-up: missing documents on request {request_id}\n"
        f"Rule: {rule_name}\n"
        f"Owner: {owner}\n"
        f"Priority: {priority}\n"
        f"Submitted: {submitted}\n"
        "\n"
        f"Hi {owner},\n"
        "\n"
        f"Request {request_id} is flagged as missing one or more required documents, "
        "which is holding up its progress. Please upload the outstanding documentation "
        "or reply with a status update so we can keep this moving.\n"
        "\n"
        f"This is an automated reminder generated by the OpsPilot {rule_name} rule.\n"
    )


def run(
    data_path: Path,
    outbox_dir: Path,
    audit_log: Path,
    rule_name: str = RULE_NAME,
    *,
    dry_run: bool = False,
    max_actions: int | None = None,
    window_days: int | None = None,
    now: _dt.datetime | None = None,
) -> dict:
    if not data_path.exists():
        raise FileNotFoundError(f"Requests CSV not found: {data_path}")

    now = now or _dt.datetime.now()
    timestamp = now.isoformat(timespec="seconds")

    last_seen = load_key_last_seen(audit_log)
    handled = handled_keys(last_seen, now, window_days)

    scanned = 0
    missing = 0
    written = 0
    skipped = 0
    capped = 0

    if not dry_run:
        outbox_dir.mkdir(parents=True, exist_ok=True)

    # Crash-safety: append each action row immediately after its outbox file is
    # written (and flush), so a mid-run failure never leaves a written follow-up
    # unrecorded -- which would cause a re-send next run. The audit file/handle is
    # opened lazily on the FIRST action, so a run with zero actions creates nothing,
    # and the header is decided by actual file contents (missing or empty), not mere
    # existence -- a zero-byte leftover still gets a header.
    audit_handle = None
    audit_writer = None

    def _audit_writer():
        nonlocal audit_handle, audit_writer
        if audit_handle is None:
            need_header = (not audit_log.exists()) or audit_log.stat().st_size == 0
            audit_handle = audit_log.open("a", newline="", encoding="utf-8")
            audit_writer = csv.writer(audit_handle)
            if need_header:
                audit_writer.writerow(AUDIT_HEADER)
                audit_handle.flush()
        return audit_writer

    # When a re-trigger window is in effect, a later chase must produce a distinct
    # artifact rather than silently overwriting the first message.
    name_suffix = f"_{now.date().isoformat()}" if window_days is not None else ""

    try:
        with data_path.open("r", newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                scanned += 1
                if not _is_true(row.get("required_documents_missing")):
                    continue
                missing += 1

                request_id = (row.get("request_id") or "").strip()
                if not request_id:
                    continue

                key = idempotency_key(request_id, rule_name)
                if key in handled:
                    skipped += 1
                    continue

                # Circuit breaker: never fire more than max_actions in one run, so a
                # data glitch that flags everything cannot blast the whole file.
                if max_actions is not None and written >= max_actions:
                    capped += 1
                    continue

                # Mark handled immediately so duplicate request_ids in the same file
                # cannot double-write within a single run.
                handled.add(key)

                outbox_file = outbox_dir / f"{_safe_slug(request_id)}_{_safe_slug(rule_name)}{name_suffix}.txt"
                # Defense in depth: never write outside the outbox directory.
                if not outbox_file.resolve().is_relative_to(outbox_dir.resolve()):
                    raise ValueError(f"Refusing to write outside outbox: {outbox_file}")

                if dry_run:
                    written += 1
                    continue

                outbox_file.write_text(build_followup_message(row, rule_name), encoding="utf-8")
                writer = _audit_writer()
                writer.writerow(
                    [timestamp, request_id, rule_name, key, "followup_message_written", str(outbox_file)]
                )
                audit_handle.flush()
                written += 1
    finally:
        if audit_handle is not None:
            audit_handle.close()

    return {
        "scanned": scanned,
        "missing": missing,
        "written": written,
        "skipped": skipped,
        "capped": capped,
        "dry_run": dry_run,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    root = _repo_root()
    parser = argparse.ArgumentParser(
        description=(
            "Detect OpsPilot requests missing required documents, write one "
            "follow-up message per request into an outbox, and audit-log each "
            "action with an idempotency key (safe to re-run)."
        )
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=root / "data" / "opspilot_requests.csv",
        help="Path to opspilot_requests.csv (default: data/opspilot_requests.csv).",
    )
    parser.add_argument(
        "--outbox",
        type=Path,
        default=root / "outbox",
        help="Directory to write follow-up messages into (default: outbox/).",
    )
    parser.add_argument(
        "--audit-log",
        type=Path,
        default=root / "audit_log.csv",
        help="Audit log CSV to append actions to (default: audit_log.csv).",
    )
    parser.add_argument(
        "--rule-name",
        default=RULE_NAME,
        help=f"Rule name used in the idempotency key (default: {RULE_NAME}).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would be sent without writing any files or audit rows.",
    )
    parser.add_argument(
        "--max-actions",
        type=int,
        default=None,
        help="Circuit breaker: stop after this many new follow-ups in one run.",
    )
    parser.add_argument(
        "--window-days",
        type=int,
        default=None,
        help=(
            "Allow a request to be chased again once its last follow-up is older "
            "than N days (reminder ladder). Default: never re-send (fully idempotent)."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    result = run(
        args.data,
        args.outbox,
        args.audit_log,
        args.rule_name,
        dry_run=args.dry_run,
        max_actions=args.max_actions,
        window_days=args.window_days,
    )
    verb = "would be written" if result["dry_run"] else "written"
    print("Missing-document follow-up automation complete." + (" [DRY RUN]" if result["dry_run"] else ""))
    print(f"  Requests scanned:          {result['scanned']}")
    print(f"  Missing-document flags:    {result['missing']}")
    print(f"  New follow-ups {verb}:  {result['written']}")
    print(f"  Already handled (skipped): {result['skipped']}")
    if result["capped"]:
        print(f"  Held back by --max-actions: {result['capped']}")
    print(f"  Outbox: {args.outbox}")
    print(f"  Audit log: {args.audit_log}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
